spring:
  profiles:
    active: ${ACTIVE_PROFILE}
---

spring:
  profile: production
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
server:
  port: 9001

persistCount: 50
counterId: File count
schema: P2PFS
tableName: counter

---
spring:
  profile: development
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
server:
    port: 8081

persistCount: 5
counterId: File count
schema: P2PFS
tableName: counter