spring:
  profiles:
    active: ${ACTIVE_PROFILE}
---

spring:
  profile: production
  datasource:
    url: jdbc:postgresql://tiny.db.elephantsql.com:5432/${DB_USERNAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
server:
  port: 8080

persistCount: 10
counterId: File count
schema: P2PFS
tableName: counter

---
spring:
  profile: development
  datasource:
    url: jdbc:postgresql://tiny.db.elephantsql.com:5432/${DB_USERNAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
server:
    port: 8080

persistCount: 10
counterId: File count
schema: P2PFS
tableName: counter